import 'package:cloud_firestore/cloud_firestore.dart';

class ChatMessage {
  String senderId;
  String message;
  String? image;
  bool isAutoGenerated;
  bool isGroup;
  ChatWindowInfo groupInfo;
  ChatWindowInfo senderInfo;
  List<String> receivers;
  List<String> views;
  Timestamp createdAt;

  ChatMessage({
    required this.senderId,
    required this.message,
    required this.isAutoGenerated,
    required this.isGroup,
    required this.groupInfo,
    this.image,
    required this.senderInfo,
    required this.receivers,
    required this.views,
    required this.createdAt,
  });

  ChatMessage copyWith({
    String? senderId,
    String? message,
    bool? isAutoGenerated,
    bool? isGroup,
    ChatWindowInfo? groupInfo,
    String? image,
    ChatWindowInfo? senderInfo,
    List<String>? receivers,
    List<String>? views,
    Timestamp? createdAt,
  }) =>
      ChatMessage(
        senderId: senderId ?? this.senderId,
        message: message ?? this.message,
        isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
        isGroup: isGroup ?? this.isGroup,
        image: image ?? this.image,
        groupInfo: groupInfo ?? this.groupInfo,
        senderInfo: senderInfo ?? this.senderInfo,
        receivers: receivers ?? this.receivers,
        views: views ?? this.views,
        createdAt: createdAt ?? this.createdAt,
      );

  factory ChatMessage.fromJson(Map<String, dynamic> json) => ChatMessage(
        senderId: json["senderId"],
        message: json["message"],
        isAutoGenerated: json["isAutoGenerated"],
        isGroup: json["isGroup"],
        image: json["image"],
        groupInfo: ChatWindowInfo.fromJson(json["groupInfo"]),
        senderInfo: ChatWindowInfo.fromJson(json["senderInfo"]),
        receivers: List<String>.from(json["receivers"].map((x) => x)),
        views: List<String>.from(json["views"].map((x) => x)),
        createdAt: json["createdAt"],
      );

  Map<String, dynamic> toJson() => {
        "senderId": senderId,
        "message": message,
        "isAutoGenerated": isAutoGenerated,
        "isGroup": isGroup,
        "image": image,
        "groupInfo": groupInfo.toJson(),
        "senderInfo": senderInfo.toJson(),
        "receivers": List<dynamic>.from(receivers.map((x) => x)),
        "views": List<dynamic>.from(views.map((x) => x)),
        "createdAt": createdAt,
      };
}

class ChatWindowInfo {
  String id;
  String avatar;
  String desc;
  String name;

  ChatWindowInfo({
    required this.id,
    required this.avatar,
    required this.desc,
    required this.name,
  });

  ChatWindowInfo copyWith({
    String? id,
    String? avatar,
    String? desc,
    String? name,
  }) =>
      ChatWindowInfo(
        id: id ?? this.id,
        avatar: avatar ?? this.avatar,
        desc: desc ?? this.desc,
        name: name ?? this.name,
      );

  factory ChatWindowInfo.fromJson(Map<String, dynamic> json) => ChatWindowInfo(
        id: json["id"],
        avatar: json["avatar"],
        desc: json["desc"],
        name: json["name"],
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "avatar": avatar,
        "desc": desc,
        "name": name,
      };
}

class UserChatMessage {
  ChatMessage latestMessage;
  int unread;

  UserChatMessage({
    required this.unread,
    required this.latestMessage,
  });
}
