import 'package:cached_network_image/cached_network_image.dart';
import 'package:e_connect_mobile/data/models/chat.dart';
import 'package:e_connect_mobile/ui/screens/chat/chat_details.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import '../../../helpers/ui_utils.dart';

class ChatRoomAppbar extends StatelessWidget {
  final UserChatMessage user;
  final bool iAmReceiver;
  final String currentUserId;

  const ChatRoomAppbar({
    super.key,
    required this.user,
    required this.iAmReceiver,
    required this.currentUserId,
  });

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      bottom: false,
      child: Container(
        padding: EdgeInsets.symmetric(horizontal: 20.w, vertical: 10.h),
        child: Row(
          children: [
            GestureDetector(
              onTap: () {
                popPage(context);
              },
              child: const Icon(Icons.arrow_back_ios),
            ),
            addHorizontalSpace(10),
            CircleAvatar(
              radius: 22.r,
              foregroundImage: CachedNetworkImageProvider(
                iAmReceiver
                    ? user.latestMessage.senderInfo.avatar
                    : user.latestMessage.groupInfo.avatar,
              ),
            ),
            addHorizontalSpace(10),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    iAmReceiver
                        ? user.latestMessage.senderInfo.name
                        : user.latestMessage.groupInfo.name,
                    maxLines: 1,
                    style: TextStyle(
                      fontSize: 18.sp,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                  Text(
                    user.latestMessage.isAutoGenerated
                        ? iAmReceiver
                            ? user.latestMessage.senderInfo.desc
                            : user.latestMessage.groupInfo.desc
                        : "${getTimeAgo(user.latestMessage.createdAt, enshort: false)}",
                  ),
                ],
              ),
            ),
            addHorizontalSpace(10),
            ClipRRect(
              borderRadius: BorderRadius.circular(50),
              child: Material(
                child: InkWell(
                  onTap: () => pushPage(
                    context,
                    to: ChatDetails(
                      description: iAmReceiver
                          ? user.latestMessage.senderInfo.desc
                          : user.latestMessage.groupInfo.desc,
                      name: iAmReceiver
                          ? user.latestMessage.senderInfo.name
                          : user.latestMessage.groupInfo.name,
                      profile: iAmReceiver
                          ? user.latestMessage.senderInfo.avatar
                          : user.latestMessage.groupInfo.avatar,
                 
                      isGroup: user.latestMessage.isGroup,
           
                      currentUserId: currentUserId,
                    ),
                  ),
                  child: Padding(
                    padding: EdgeInsets.all(8.r),
                    child: const Icon(
                      Icons.more_vert,
                    ),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
